import car from "../../assets/banner.png";
export const cars = [
  {
    name: "Hyundai Accent",
    type: "Crossover",
    price: 74,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Hyundai I10",
    type: "Hatchback",
    price: 74,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "MG 3",
    type: "Station Wagon",
    price: 41,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Toyota Yaris",
    type: "Hatchback",
    price: 35,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Toyota Corolla",
    type: "Compact",
    price: 57,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Honda Civic",
    type: "Hatchback",
    price: 76,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Honda City",
    type: "Crossover",
    price: 78,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Kia Rio",
    type: "Sedan",
    price: 42,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Kia Sportage",
    type: "Compact",
    price: 38,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Ford Focus",
    type: "Family MPV",
    price: 33,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Ford Escape",
    type: "SUV",
    price: 69,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Chevrolet Spark",
    type: "Hatchback",
    price: 56,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Chevrolet Malibu",
    type: "Intermediate",
    price: 32,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Nissan Micra",
    type: "Family MPV",
    price: 57,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Nissan Altima",
    type: "Compact",
    price: 67,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Mazda 3",
    type: "Station Wagon",
    price: 42,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Mazda CX-5",
    type: "Family MPV",
    price: 49,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "BMW 3 Series",
    type: "Compact",
    price: 46,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "BMW X1",
    type: "Hatchback",
    price: 76,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Mercedes A-Class",
    type: "4x4",
    price: 67,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Mercedes C-Class",
    type: "Crossover",
    price: 50,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Audi A3",
    type: "4x4",
    price: 63,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Audi Q2",
    type: "Family MPV",
    price: 66,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Volkswagen Golf",
    type: "Family MPV",
    price: 31,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Volkswagen Polo",
    type: "Hatchback",
    price: 60,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Skoda Octavia",
    type: "4x4",
    price: 44,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Skoda Fabia",
    type: "Crossover",
    price: 77,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Peugeot 208",
    type: "Station Wagon",
    price: 51,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Peugeot 3008",
    type: "Hatchback",
    price: 62,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Renault Clio",
    type: "Intermediate",
    price: 63,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Renault Captur",
    type: "SUV",
    price: 38,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Suzuki Swift",
    type: "Sedan",
    price: 68,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Suzuki Vitara",
    type: "Crossover",
    price: 35,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Subaru Impreza",
    type: "Crossover",
    price: 49,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Subaru Forester",
    type: "SUV",
    price: 36,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Mitsubishi Mirage",
    type: "4x4",
    price: 78,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Mitsubishi Outlander",
    type: "Sedan",
    price: 74,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Jeep Compass",
    type: "Intermediate",
    price: 69,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Jeep Wrangler",
    type: "Family MPV",
    price: 42,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Tesla Model 3",
    type: "SUV",
    price: 78,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Tesla Model Y",
    type: "Station Wagon",
    price: 52,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Fiat 500",
    type: "4x4",
    price: 60,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Fiat Tipo",
    type: "Compact",
    price: 49,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Volvo S60",
    type: "SUV",
    price: 39,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Volvo XC40",
    type: "4x4",
    price: 75,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Seat Ibiza",
    type: "SUV",
    price: 61,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Seat Arona",
    type: "Station Wagon",
    price: 39,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Opel Corsa",
    type: "Sedan",
    price: 79,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Opel Astra",
    type: "Hatchback",
    price: 57,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
  {
    name: "Citroen C3",
    type: "Compact",
    price: 55,
    image: car,
    images: [car, car, car],
    fuel: "Petrol",
    gearbox: "Automatic",
    doors: 4,
    mileage: "200 Km",
    deposit: "Not required",
    engine: "1.5L Engine",
    airbags: "2 Airbags",
  },
];
